import React, { Fragment, useState } from "react";
import Head from "next/head";
import Layouts from "@components/layouts/index";
import Card from "@components/card";
import Link from "next/link";
import { Flex, Center, Grid, Box, Text, Image } from "@chakra-ui/react";

export default function Manual() {
  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layouts>
        <div className="page-hero page-container " id="page-hero">
          <div className="padding text-center">
            <Center gap={2} alignItems="center">
              <Image src="/image/icon_3/information.png" boxSize="40px" />
              <Text fontSize="4xl"> คู่มือการใช้งาน</Text>
            </Center>
          </div>
        </div>
        <div className="page-content page-container">
          <Flex direction="column" gap="4" p="4">
            <Grid templateColumns="repeat(2, 1fr)" gap={6}>
              <Box
                borderWidth="1px"
                p="4"
                borderRadius="xl"
                overflow="hidden"
                bg="#b8e3ff"
              >
                <Text fontSize='3xl' as='b' color='#000'>คู่มือการใช้งาน SMS</Text>
                <Flex  pl='10px' pt='10px'>
                <Image cl src="/image/icon_3/manual-book.png" boxSize="30px" />
                <Link href='#' >
                <a>
                 <Text fontSize='2xl' as='b' pl='10px' color='#000'> วิธีการใช้งาน SMS</Text>
                </a>
                </Link>
                </Flex >
                <Flex  pl='10px' pt='10px'>
                <Image cl src="/image/icon_3/completed-task.png" boxSize="30px" />
                <Link href='#' >
                <a>
                 <Text fontSize='2xl' as='b' pl='10px' color='#000'> วิธีการจัดการรายชื่อ SMS</Text>
                </a>
                </Link>
                </Flex >
                <Flex  pl='10px' pt='10px'>
                <Image cl src="/image/icon_3/browser.png" boxSize="30px" />
                <Link href='#' >
                <a>
                 <Text fontSize='2xl' as='b' pl='10px' color='#000'> วิธีการจัดการเทมเพลตข้อความ</Text>
                </a>
                </Link>
                </Flex >
                <Box h='20px'></Box>
                <Text fontSize='3xl' as='b' color='#000'>คู่มือการใช้งาน OTP</Text>
                <Flex  pl='10px' pt='10px'>
                <Image cl src="/image/icon_3/manual-book.png" boxSize="30px" />
                <Link href='#' >
                <a>
                 <Text fontSize='2xl' as='b' pl='10px' color='#000'> วิธีการใช้งาน OTP</Text>
                </a>
                </Link>
                </Flex >
                <Box h='20px'></Box>
                <Flex  pl='10px' pt='10px'>
                <Image cl src="/image/icon_3/credit.png" boxSize="30px" />
                <Link href='#' >
                <a>
                 <Text fontSize='2xl' as='b' pl='10px' color='#000'> วิธีการเติมเครดิต</Text>
                </a>
                </Link>
                </Flex >
                <Flex  pl='10px' pt='10px'>
                <Image cl src="/image/icon_3/group.png" boxSize="30px" />
                <Link href='#' >
                <a>
                 <Text fontSize='2xl' as='b' pl='10px' color='#000'> วิธีการเพิ่มชื่อผู้ส่ง</Text>
                </a>
                </Link>
                </Flex >
              </Box>
              <Box
                borderWidth="1px"
                p="4"
                borderRadius="xl"
                overflow="hidden"
              ><iframe width="560" height="315" src="https://www.youtube.com/embed/mC7aTvb9EhE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></Box>
            </Grid>
          </Flex>
        </div>
      </Layouts>
    </Fragment>
  );
}
