import React, { Fragment} from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Layouts from '@components/layouts/index'
import styles from '../styles/Home.module.css'
import Blog from '@components/blog'


export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layouts>
          <div className='page-content page-container'>
            <div className='padding'>
              <Blog></Blog>
            </div>
          </div>
      </Layouts>
    </Fragment>
  )
}
