import React, { Fragment, useEffect, useState } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import Logo from '@components/Logo'
import { Box } from "@chakra-ui/react";

const Forgot = () => {

    return (
        <Fragment>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Box className="layout-row bg_yello">
          <div className="flex">
            <div className="w-xl w-auto-sm mx-auto py-5 ">
                <div className="p-4 d-flex flex-column h-100">
                    <Logo/>
                </div>
                <div className="card m-3">
                    <div id="content-body">
                        <div className="p-3 ">
                            <h5>ลืมรหัสผ่าน</h5>
                            <p>
                                <small className="text-muted">กรอกหมายเลขโทรศัพท์ในระบบของคุณ</small>
                            </p>
                            <form className="" role="form" action="/otp">
                                <div className="form-group">
                                    <label>Phone Number</label>
                                    <input type="text" className="form-control" placeholder="Phone Number"/>
                                </div>
                                <button type="submit" className="btn btn-pum mb-4 mt-4">ส่ง</button>
                            </form>
                        </div>
                    </div>
                </div>
                <div className="text-center ">&copy; Copyright. Pumppang</div>
            </div>
        </div>
          </Box>
        </Fragment>
    )

}


export async function getServerSideProps(context) {
    return {
        props: {}, // will be passed to the page component as props
      }
}
    
export default Forgot