import React, { Fragment, useEffect, useState } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import Layouts from '@components/layouts/index'
import {
    Box
  } from "@chakra-ui/react";

const Home = () => {

    return (
        <Fragment>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Box className="layout-row bg_yello">
          <div className="flex">
            <div className="w-xl w-auto-sm mx-auto py-5 ">
                <div className="p-4 d-flex flex-column h-100">
                    <Box className="navbar-brand align-self-center">
                        <img src="/image/Logo_Pumppang.png" className="img-fluid"/>
                    </Box>
                </div>
                <div className="card m-3">
                    <div id="content-body">
                        <div className="p-3 ">
                            <h5>ยินดีต้อนรับ</h5>
                            <p>
                                <small className="text-muted">เข้าสู่ระบบเพื่อจัดการบัญชีของคุณ</small>
                            </p>
                            <form className="" role="form" action="index.html">
                                <div className="form-group">
                                    <label>Phone Number</label>
                                    <input type="text" className="form-control" placeholder="Phone Number"/>
                                </div>
                                <div className="form-group set_bot_login">
                                    <label>Password</label>
                                    <input type="password" className="form-control" placeholder="Password"/>
                                    <div className="set_bot_login my-3 text-right">
                                        <a href="forgot-password.html" className="text-muted">ลืมรหัสผ่าน?</a>
                                    </div>
                                </div>
                                <div className="checkbox mb-3 ">
                                    <label className="ui-check">
                                        <input type="checkbox"/>
                                        <i></i> จดจำฉันไว้
                                    </label>
                                </div>
                                <Link href="/dashboard">
                                    <a className="btn btn-pum mb-4">เข้าสู่ระบบ</a>
                                </Link>
                                <div>คุณยังไม่มีบัญชี?
                                    <Link href="/register">
                                    <a className="text-primary">สมัครสมาชิก</a>
                                    </Link>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div className="text-center ">&copy; Copyright. Pumppang</div>
            </div>
        </div>
          </Box>
        </Fragment>
    )

}


export async function getServerSideProps(context) {
    return {
        props: {}, // will be passed to the page component as props
      }
}
    
export default Home