import React, { Fragment, useEffect, useState } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import Logo from '@components/Logo'
import {
    Box
  } from "@chakra-ui/react";

const Otp = () => {

    return (
        <Fragment>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Box className="layout-row bg_yello">
          <div className="flex">
            <div className="w-xl w-auto-sm mx-auto py-5 ">
                <div className="p-4 d-flex flex-column h-100">
                    <Logo/>
                </div>
                <div className="card m-3">
                    <div id="content-body">
                        <div className="p-3 ">
                            <h5>กรอกหมายเลข OTP</h5>
                            <p>
                                <small className="text-muted">ระบบจะส่งหมายเลข OTP ไปยังโทรศัพท์ของคุณ</small>
                            </p>
                            <form className="" role="form" action="/new_password">
                                <div className="form-group">
                                    <label>หมายเลขอ้างอิง OTP</label>
                                    <input type="text" className="form-control" />
                                </div>
                                <div className="form-group row get_pad_r_l mt-2">
                                    <input type="text" className="form-control inputs otp1 verifyPhone "  name="otp1" />


                                    <input type="text" className="form-control inputs otp2 verifyPhone "  name="otp2" />


                                    <input type="text" className="form-control inputs otp3 verifyPhone "  name="otp3" />


                                    <input type="text" className="form-control inputs otp4 verifyPhone "  name="otp4" />


                                    <input type="text" className="form-control inputs otp5 verifyPhone "  name="otp5" />


                                    <input type="text" className="form-control inputs otp6 verifyPhone "  name="otp6" />

                                </div>
                                
                                <button type="submit" className="btn btn-pum mb-4">ยืนยัน OTP</button>
                                
                            </form>
                        </div>
                    </div>
                </div>
                <div className="text-center ">&copy; Copyright. Pumppang</div>
            </div>
        </div>
          </Box>
        </Fragment>
    )

}


export async function getServerSideProps(context) {
    return {
        props: {}, // will be passed to the page component as props
      }
}
    
export default Otp