import React, { Fragment, useEffect, useState } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import Logo from '@components/Logo'
import {
    Box
  } from "@chakra-ui/react";

const Register = () => {

    return (
        <Fragment>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Box className="layout-row bg_yello">
          <div className="flex">
            <div className="w-xl w-auto-sm mx-auto py-5 ">
                <div className="p-4 d-flex flex-column h-100">
                    <Logo/>
                </div>
                <div className="card m-3">
                    <div id="content-body">
                        <div className="p-3 ">
                            <h5>สมัครสมาชิก</h5>
                            <p>
                                <small className="text-muted">ลงทะเบียนเพื่อจัดการบัญชีของคุณ</small>
                            </p>
                            <form className="" role="form" action="/dashboard">
                                <div className="form-group">
                                    <label>Phone Number</label>
                                    <input type="text" className="form-control" placeholder="Phone Number" />
                                </div>
                                <div className="form-group">
                                    <label>Username</label>
                                    <input type="text" className="form-control" placeholder="Username" />
                                </div>
                                <div className="form-group">
                                    <label>Password</label>
                                    <input type="password" className="form-control" placeholder="Password" />
                                </div>
                                <div className="form-group">
                                    <label>Confirm Password</label>
                                    <input type="password" className="form-control" placeholder="Password" />
                                </div>
                                <div className="mb-3 text-sm">
                                    <span className="text-muted">การคลิกสมัครแสดงว่าฉันยอมรับ</span>
                                    <a href="term.html" data-pjax-state="">เงื่อนไขการให้บริการ</a>
                                </div>
                                <button type="submit" className="btn btn-pum mb-4">สมัครสมาชิก</button>
                                <div>หากมีบัญชีอยู่แล้ว?
                                    <Link href="/">
                                    <a className="text-primary">เข้าสู่ระบบ</a>
                                    </Link>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div className="text-center ">&copy; Copyright. Pumppang</div>
            </div>
        </div>
          </Box>
        </Fragment>
    )

}
    
export default Register