import React, { useEffect, Fragment, useState } from "react";
import Head from "next/head";
import Layouts from "@components/layouts/index";
import Card from "@components/card";
import {
  Flex,
  Heading,
  Box,
  Link,
  Spacer,
  Text,
  Input,
  Grid,
  GridItem,
  Tabs,
  TabList,
  TabPanels,
  Tab,
  TabPanel,
  useTab,
  useMultiStyleConfig,
  Button,
  Center,
  Checkbox,
  CheckboxGrou,
  Stack,
} from "@chakra-ui/react";
import Btn_link from "@components/btn_link";
import CustomTab from '@components/CustomTab';

export default function Package() {

  

  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layouts>
        <div className="page-hero page-container " id="page-hero">
          <div className="padding text-center"></div>
        </div>
        <div className="page-content page-container">
        <div className='padding'>
          <Card>
            <Flex>
              <Box>
                <Btn_link title="กลับหน้าแพ็คเกจจ" url="/payment/payment_sms"/>
              </Box>
              <Spacer />
              <Box>
                <Text fontSize="3xl" as="b">
                  รายละเอียดการสั่งซื้อ
                </Text>
              </Box>
              <Spacer />
            </Flex>
            <Box p="4" className="row">
              <Box p="4" className="col-md-7">
                <Text fontSize="2xl">ข้อมูลผู้สั่งซื้อ</Text>
                <Box
                  borderWidth="1px"
                  p="4"
                  borderRadius="xl"
                  overflow="hidden"
                  bg="#b8e3ff"
                >
                  <Tabs align="center" justify="center">
                    <TabList alignItems="center" className="set_new_tap">
                      <CustomTab className="f-24"> บุคคลธรรมดา</CustomTab>
                      <CustomTab className="f-24"> นิติบุคคล</CustomTab>
                    </TabList>
                    <TabPanels>
                      <TabPanel>
                        <div className="form-row text-left">
                          <div className="form-group col-md-6">
                            <label>
                              ชื่อ-นามสกุล
                              <span className="text-danger">*</span>
                            </label>
                            <input
                              type="text"
                              className="form-control in_br"
                              placeholder="ระบุชื่อ-นามสกุล"
                            />
                          </div>
                          <div className="form-group col-md-6">
                            <label>เลขบัตรประชาชน</label>
                            <input
                              type="text"
                              className="form-control in_br"
                              placeholder="ระบุเลขบัตรประชาชน"
                            />
                          </div>
                        </div>
                        <Box h="4"></Box>
                        <div className="form-row text-left">
                          <div className="form-group col-md-6">
                            <label>
                              เบอร์โทรศัพท์
                              <span className="text-danger">*</span>
                            </label>
                            <input
                              type="text"
                              className="form-control in_br"
                              placeholder="ระบุเบอร์โทรศัพท์"
                            />
                          </div>
                          <div className="form-group col-md-6">
                            <label>
                              E-mail <span className="text-danger">*</span>
                            </label>
                            <input
                              type="text"
                              className="form-control in_br"
                              placeholder="ระบุอีเมล"
                            />
                          </div>
                        </div>
                        <Box h="2"></Box>
                        <div className="form-row p-2">
                          <label>
                            ที่อยู่ <span className="text-danger">*</span>
                          </label>
                          <textarea
                            className="form-control in_br2"
                            rows="7"
                            placeholder="ระบุที่อยู่"
                          ></textarea>
                        </div>
                      </TabPanel>
                      <TabPanel>
                        <div className="form-row text-left">
                          <div className="form-group col-md-6">
                            <label>
                              ชื่อ-นามสกุล
                              <span className="text-danger">*</span>
                            </label>
                            <input
                              type="text"
                              className="form-control in_br"
                              placeholder="ระบุชื่อ-นามสกุล"
                            />
                          </div>
                          <div className="form-group col-md-6">
                            <label>
                              ชื่อผู้ติดต่อ
                              <span className="text-danger">*</span>
                            </label>
                            <input
                              type="text"
                              className="form-control in_br"
                              placeholder="ระบุชื่อผู้ติดต่อ"
                            />
                          </div>
                        </div>
                        <Box h="3"></Box>
                        <div className="form-row text-left">
                          <div className="form-group col-md-6">
                            <label>
                              เลขประจำตัวผู้เสียภาษี
                              <span className="text-danger">*</span>
                            </label>
                            <input type="text" className="form-control in_br" placeholder="ระบุเลขประจำตัวผู้เสียภาษี" />
                          </div>
                          <div className="form-group col-md-6">
                            <label>
                              สาขา <span className="text-danger">*</span>
                            </label>
                            <input type="text" className="form-control in_br" placeholder="ระบุสาขา" />
                          </div>
                        </div>
                        <Box h="3"></Box>
                        <div className="form-row text-left">
                          <div className="form-group col-md-6">
                            <label>
                              เบอร์โทรศัพท์
                              <span className="text-danger">*</span>
                            </label>
                            <input
                              type="text"
                              className="form-control in_br"
                              placeholder="ระบุเบอร์โทรศัพท์"
                            />
                          </div>
                          <div className="form-group col-md-6">
                            <label>
                              E-mail <span className="text-danger">*</span>
                            </label>
                            <input
                              type="text"
                              className="form-control in_br"
                              placeholder="ระบุอีเมล"
                            />
                          </div>
                        </div>
                        <Box h="2"></Box>
                        <div className="form-row p-2">
                          <label>
                            ที่อยู่ <span className="text-danger">*</span>
                          </label>
                          <textarea
                            className="form-control in_br2"
                            rows="7"
                            placeholder="ระบุที่อยู่"
                          ></textarea>
                          <Checkbox colorScheme="green" pt="3" className="bg-w">
                            ต้องการใบกำกับภาษี
                          </Checkbox>
                        </div>
                      </TabPanel>
                    </TabPanels>
                  </Tabs>
                </Box>
              </Box>

              <Box p="4" className="col-md-5">
                <Text fontSize="2xl">รายการสั่งซื้อ</Text>
                <Box
                  borderWidth="1px"
                  p="4"
                  borderRadius="xl"
                  overflow="hidden"
                  bg="#b8e3ff"
                >
                  <Text fontSize="5xl" color="#000" className="text-center">
                    {" "}
                    แพ็คเกจ C 27,080 เครดิต{" "}
                  </Text>
                  <Text fontSize="2xl" color="#000" className="text-center">
                    {" "}
                    อายุการใช้งานย 1 ปี ( 3Sender Name ){" "}
                  </Text>
                  <Box
                    borderWidth="1px"
                    p={[0,10]}
                    borderRadius="xl"
                    overflow="hidden"
                    bg="#fff"
                  >
                    <Flex>
                      <Box><Text as='b' fontSize='2xl'>รายการ</Text></Box>
                      <Spacer />
                      <Box><Text as='b' fontSize='2xl'>จำนวนเงิน </Text></Box>
                    </Flex>
                    <Flex>
                      <Box>แพ็คเกจ C</Box>
                      <Spacer />
                      <Box>15,000.-</Box>
                    </Flex>
                    <Flex >
                      <Box>แพ็คเกจ C</Box>
                      <Spacer />
                      <Box>15,000.-</Box>
                    </Flex>
                    <Flex>
                      <Box>แพ็คเกจ C</Box>
                      <Spacer />
                      <Box>15,000.-</Box>
                    </Flex>
                    <Box h="10"></Box>
                    <hr></hr>
                    <Box h="5"></Box>
                    <Flex>
                      <Box><Text as='b' fontSize='2xl'>ยอดรวมสุทธิ</Text></Box>
                      <Spacer />
                      <Box><Text as='b' fontSize='2xl'>15,600.- </Text></Box>
                    </Flex>
                  </Box>
                </Box>
              </Box>

              <Box className="col-md-12">
              <Link href="/payment/choose_payment">
                  <a className="btn_radius pull-right btn btn-sm btn-pum font-22">
                     ถัดไป <i className="fa fa-angle-right faicon-next"></i>
                  </a>
                </Link>
              </Box>
            </Box>
          </Card>
        </div>
        </div>
      </Layouts>
    </Fragment>
  );
}
