import React, { Fragment, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Layouts from "@components/layouts/index";
import Card from "@components/card";
import Btn_icon_xl from "@components/Btn_icon_xl";
import countriesData from "@components/data/opt";
import Credit_box from "@components/credit_box";
import Box_price from "@components/Box_price";
import { Flex, Spacer, Box } from "@chakra-ui/react";
import PaymentHistory_blue from '@components/Modal/PaymentHistory_blue';

export default function Payment() {
  const [countries] = useState([...countriesData]);
  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layouts>
        <div className="page-hero page-container " id="page-hero">
          <div className="padding text-center">
            <Btn_icon_xl
              icon="/image/icon_3/text-message (1).png"
              text="เครดิต SMS"
              url="/payment/payment_sms"
              bg="blue_active"
            />
            <Btn_icon_xl
              icon="/image/icon_3/mobile.png"
              text="เครดิต OTP"
              url="/payment/payment_otp"
            />
          </div>
        </div>
        <div className="page-content page-container">
          <Card>
            <Flex justifyContent="center" gap="4">
              <Credit_box title="เครดิตคงเหลือ" credit="1282" url="" />
              <Credit_box title="แพ็คเกต" credit="BASIC" url="" />
              <PaymentHistory_blue/>
            </Flex>
            <Box height="5" />
            <hr></hr>
            <Box height="5" />
            <Flex justifyContent="center" gap="4">
              <Box_price title="แพ็คเกจ A" type="product" price="1,500" />
              <Box_price title="แพ็คเกจ B" type="product" price="5,000"/>
              <Box_price title="แพ็คเกจ C" type="recommended" price="15,000"/>
              <Box_price title="แพ็คเกจ D" type="product" price="50,000"/>
            </Flex>
          </Card>
        </div>
      </Layouts>
    </Fragment>
  );
}
