import React, { useEffect, Fragment, useState } from "react";
import Head from "next/head";
import Layouts from "@components/layouts/index";
import Card from "@components/card";
import {
  Flex,
  Image,
  Box,
  Link,
  Spacer,
  Text,
  Input,
  Grid,
  GridItem,
  Tabs,
  TabList,
  TabPanels,
  Tab,
  TabPanel,
  useTab,
  useMultiStyleConfig,
  Button,
  Center,
  Checkbox,
  CheckboxGrou,
  Stack,
  Table,
  Thead,
  Tbody,
  Tfoot,
  Tr,
  Th,
  Td,
  TableCaption,
  TableContainer,
} from "@chakra-ui/react";
import Btn_link from "@components/btn_link";
import Dropzone from "react-dropzone";
import DatePicker from "react-datepicker";
import "react-datepicker/dist/react-datepicker.css";
import Btn_icon_b from '@components/Btn_icon_b';

export default function PaymentDetail() {
    const [startDate, setStartDate] = useState(new Date());
  const [fileNames, setFileNames] = useState([]);
  const handleDrop = (acceptedFiles) =>
    setFileNames(acceptedFiles.map((file) => file.name));
  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layouts>
        <div className="page-content page-container">
        <div className='padding'>
          <Card>
            <Flex>
              <Box>
                <Btn_link title="ย้อนกลับ" url="/payment/payment_sms" />
              </Box>
              <Spacer />
              <Box>
                <Text fontSize="3xl" as="b">
                  สรุปข้อมูลการสั่งซื้อ
                </Text>
              </Box>
              <Spacer />
            </Flex>
            <Box p="4" className="row">
              <Box p="4" className="col-md-6">
                <Text fontSize="2xl">ข้อมูลผู้สั่งซื้อ</Text>
                <Box
                  borderWidth="1px"
                  p="2"
                  borderRadius="xl"
                  overflow="hidden"
                  bg="#b8e3ff"
                >
                  <Box
                    borderWidth="1px"
                    p={[0, 3]}
                    borderRadius="xl"
                    overflow="hidden"
                    bg="#fff"
                  >
                    <TableContainer>
                      <Table size="sm" fontSize={16}>
                        <Tbody>
                          <Tr>
                            <Td className="no_border">ชื่อ - นามสกุล</Td>
                            <Td className="no_border">:</Td>
                            <Td className="no_border">สหรัฐ เจริญมี</Td>
                          </Tr>
                          <Tr>
                            <Td className="no_border">เลขประจำตัวประชาชน</Td>
                            <Td className="no_border">:</Td>
                            <Td className="no_border">1101401045236</Td>
                          </Tr>
                          <Tr>
                            <Td className="no_border">เบอร์โทรศัพท์</Td>
                            <Td className="no_border">:</Td>
                            <Td className="no_border">0902160080</Td>
                          </Tr>
                          <Tr>
                            <Td className="no_border">E-mail</Td>
                            <Td className="no_border">:</Td>
                            <Td className="no_border">kim.kundad@gmail.com</Td>
                          </Tr>
                          <Tr>
                            <Td className="no_border">ที่อยู่</Td>
                            <Td className="no_border">:</Td>
                            <Td className="no_border">
                              20/426 PRUKSAVILLE รามคำแหง - วงแหวน (ซอยมิสทีน)
                              ถนน ราษฎร์พัฒนา แขวง สะพานสูง เขต สะพานสูง จังหวัด
                              กรุงเทพมหานคร 10240
                            </Td>
                          </Tr>
                        </Tbody>
                      </Table>
                    </TableContainer>
                  </Box>
                </Box>
                <Box h="5"></Box>
                <Text fontSize="2xl">รายละเอียดการสั่งซื้อ</Text>
                <Box
                  borderWidth="1px"
                  p="2"
                  borderRadius="xl"
                  overflow="hidden"
                  bg="#b8e3ff"
                >
                  <Box
                    borderWidth="1px"
                    p={[0, 3]}
                    borderRadius="xl"
                    overflow="hidden"
                    bg="#fff"
                  >
                    <Box textAlign="center">
                      <Text fontSize="2xl">เลขที่ใบสั่งซื้อ : SMSP0002457</Text>
                      <hr />
                      <TableContainer>
                        <Table size="sm">
                          <TableCaption mt="0">
                            <hr />
                            <Text mt="3" fontSize="xl">
                              ยอดรวมสุทธิ 16,050 บาท
                            </Text>
                          </TableCaption>
                          <Tbody>
                            <Tr>
                              <Td className="no_border">
                                แพ็คเกจ C 27,780 เครดิต
                              </Td>
                              <Td className="no_border" isNumeric>
                                15,200 บาท
                              </Td>
                            </Tr>
                            <Tr>
                              <Td className="no_border">Vat (7%)</Td>
                              <Td className="no_border" isNumeric>
                                1,050 บาท
                              </Td>
                            </Tr>
                          </Tbody>
                        </Table>
                      </TableContainer>
                    </Box>
                  </Box>
                </Box>
              </Box>
              <Box p="4" className="col-md-6">
                <Text fontSize="2xl">วิธีการชำระเงิน</Text>
                <Box
                  borderWidth="1px"
                  p="2"
                  borderRadius="xl"
                  overflow="hidden"
                  bg="#b8e3ff"
                >
                  <Box
                    borderWidth="1px"
                    p={[0, 3]}
                    borderRadius="xl"
                    overflow="hidden"
                    bg="#fff"
                  >
                    <Flex>
                      <Box>
                        <Text fontSize="2xl">ช่องทางการชำระเงิน : </Text>
                      </Box>
                      <Spacer />
                      <Box>
                        <Flex>
                          <Image className="w-30 " src='/image/1655955831-22713007.png' />
                          <Text pl="2" fontSize="2xl">
                            โอนเงินธนาคารกสิกรไทย
                          </Text>
                        </Flex>
                      </Box>
                      <Spacer />
                    </Flex>
                  </Box>
                </Box>
                <Box h="5"></Box>
                <Text fontSize="2xl">แจ้งชำระเงิน</Text>
                <Box
                  borderWidth="1px"
                  p="4"
                  borderRadius="xl"
                  overflow="hidden"
                  bg="#b8e3ff"
                >
                  <Box>
                    <div className="form-row">
                      <div className="form-group col-md-6">
                        <label>วันที่ชำระเงิน</label>
                        <DatePicker className="form-control" selected={startDate} onChange={(date) => setStartDate(date)} />
                      </div>
                      <div className="form-group col-md-6">
                        <label>เวลาชำระเงิน</label>
                        <input
                          type="text"
                          className="form-control"
                          placeholder="ระบุเวลาชำระเงิน"
                        />
                      </div>
                    </div>
                    <Box h="3"></Box>
                    <div className="form-row">
                      <div className="form-group col-md-6">
                        <label>ธนาคาร</label>

                        <select className="form-control">
                          <option value="">เลือกธนาคาร</option>
                          <option value="1">ธนาคารกสิกรไทย</option>
                          <option value="2">ธนาคารกรุงเทพ</option>
                          <option value="3">ธนาคารกรุงไทย</option>
                          <option value="4">ธนาคารทหารไทยธนชาต</option>
                          <option value="5">ธนาคารไทยพาณิชย์</option>
                          <option value="6">ธนาคารกรุงศรีอยุธยา</option>
                          <option value="7">ธนาคารเกียรตินาคินภัทร</option>
                          <option value="8">ธนาคารซีไอเอ็มบีไทย</option>
                          <option value="9">ธนาคารทิสโก้</option>
                          <option value="11">ธนาคารยูโอบี</option>
                          <option value="12">
                            ธนาคารไทยเครดิตเพื่อรายย่อย
                          </option>
                          <option value="13">ธนาคารแลนด์แอนด์ เฮ้าส์</option>
                          <option value="14">ธนาคารไอซีบีซี (ไทย)</option>
                          <option value="15">
                            ธนาคารพัฒนาวิสาหกิจขนาดกลางและขนาดย่อมแห่งประเทศไทย
                          </option>
                          <option value="16">
                            ธนาคารเพื่อการเกษตรและสหกรณ์การเกษตร
                          </option>
                          <option value="17">
                            ธนาคารเพื่อการส่งออกและนำเข้าแห่งประเทศไทย
                          </option>
                          <option value="18">ธนาคารออมสิน</option>
                          <option value="19">ธนาคารอาคารสงเคราะห์</option>
                          <option value="20">ธนาคารอิสลามแห่งประเทศไทย</option>
                        </select>
                      </div>
                      <div className="form-group col-md-6">
                        <label>จำนวนเงิน</label>
                        <input
                          type="text"
                          className="form-control"
                          placeholder="ระบุจำนวนเงิน"
                        />
                      </div>
                    </div>
                    <Text fontSize="xl">อัพโหลดหลักฐานการโอนเงิน</Text>
                  </Box>
                  <Dropzone
                    onDrop={handleDrop}
                    accept="*"
                    minSize={1024}
                    maxSize={3072000}
                  >
                    {({
                      getRootProps,
                      getInputProps,
                      isDragActive,
                      isDragAccept,
                      isDragReject,
                    }) => {
                      const additionalClass = isDragAccept
                        ? "accept"
                        : isDragReject
                        ? "reject"
                        : "";

                      return (
                        <div
                          {...getRootProps({
                            className: `dropzone ${additionalClass}`,
                          })}
                        >
                          <input {...getInputProps()} />
                          <span className="d-flex justify-content-center">
                            {isDragActive ? (
                              <Image className="w-50 " src='/image/icon_3/upload (6).png' />
                            ) : (
                              <Image className="w-50 " src='/image/icon_3/upload (6).png' />
                            )}
                          </span>
                          <p>เลือกไฟล์</p>
                        </div>
                      );
                    }}
                  </Dropzone>
                  <div>
                    <strong>Files:</strong>
                    <ul>
                      {fileNames.map((fileName) => (
                        <li key={fileName}>{fileName}</li>
                      ))}
                    </ul>
                  </div>
                </Box>
              </Box>
              <Box p="4" className="col-md-12">
                <Box className="text-center">
                <Btn_icon_b
                      icon="/image/icon_3/check copy.png" 
                      text="ยืนยัน"
                      url="#"
                      />
                </Box>
              </Box>
            </Box>
          </Card>
        </div>
        </div>
      </Layouts>
    </Fragment>
  );
}
