import React, { Fragment } from "react";
import Head from "next/head";
import Layouts from "@components/layouts/index";
import Card from "@components/card";
import CardBlue from "@components/cardBlue";
import Btn_H_sms from "@components/btn_header_sms";
import FileContact from '@components/Modal/FileContact';
import { useRef } from "react";
import {
  Link
} from "@chakra-ui/react";


export default function Sms_sender() {

  const inputFile = useRef(null) 
  const onButtonClick = () => {
    // `current` points to the mounted file input element
   inputFile.current.click();
  };

  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layouts>
        <div className="page-content page-container">
        <div className='padding'>
          <Btn_H_sms></Btn_H_sms>
          <br />
          <Card>
            <CardBlue>
              <div className="row">
                <div className="col-md-4 ">
                  <div className="form-group row">
                    <label className="col-sm-4 col-form-label">ชื่อเเคมเปญ</label>
                    <div className="col-sm-8">
                      <select className="form-control circle">
                        <option> 03 Jun 2022 [13:21:20]</option>
                        <option> 03 Jun 2022 [13:21:20]</option>
                      </select>
                    </div>
                  </div>
                </div>
                <div className="col-md-4 ">
                  <div className="form-group row">
                    <label className="col-sm-4 col-form-label">ชื่อผู้ส่ง</label>
                    <div className="col-sm-8">
                      <select className="form-control circle">
                        <option>SMSPANG</option>
                        <option>SMSPANG2</option>
                        <option>SMSPANG3</option>
                      </select>
                    </div>
                  </div>
                </div>
                <div className="col-md-4 ">
                  <div className="form-group row">
                    <label className="col-sm-4 col-form-label">รูปแบบการส่ง</label>
                    <div className="col-sm-8">
                      <select className="form-control circle">
                        <option>ส่งทันที</option>
                        <option>ส่งทันที</option>
                      </select>
                    </div>
                  </div>
                </div>
              </div>
            </CardBlue>
            <CardBlue>
              <div className="row">
                <div className="col-md-4 text-center">
                  <strong>เบอร์โทรศัพท์ที่ต้องการส่ง</strong>
                  <div className="item_head_icon top_15">
                      <a className={'tb_btn btn_radius btn btn-white btn-sender-fix'} >ระบุเอง</a>
                  </div>
                  <div className="item_head_icon top_15">
                      <FileContact/>
                  </div>
                  <div className="item_head_icon top_15">
                      <a onClick={onButtonClick} className={'tb_btn btn_radius btn btn-white btn-sender-fix'} >เลือกจากไฟล์</a>
                      <input type='file' id='file' ref={inputFile} style={{display: 'none'}}/>
                  </div>
                  <br />
                  <button className="btn btn-sender-fix btn_radius mb-1 btn-md btn-white">
                    <div className="d-flex">
                      <span>
                        <img
                          className="w-50 "
                          src="/image/icon_3/text-message (1).png"
                        />
                      </span>
                      <div className="mx-3 ">
                        <strong className="phone_item_new">
                          จำนวนเบอร์โทรศัพท์
                        </strong>
                        <small className="strong_new_price">000000</small>
                      </div>
                    </div>
                  </button>
                </div>
                <div className="col-md-8 ">
                  <div className="form-group">
                    <textarea
                      className="form-control auto_height btn_radius"
                      rows="9"
                      data-minwords="6"
                      required=""
                      placeholder="กรอกเบอร์โทรศัพท์ บรรทัดละ 1 เบอร์ ตัวอย่าง 0877777777"
                    ></textarea>
                  </div>
                  <br />
                  <Link href='/sms_service/sms_sender/sms_preview_sender'>
                  <a className="btn_radius pull-right btn btn-sm btn-pum">
                    ถัดไป
                  </a>
                  </Link>
                </div>
              </div>
            </CardBlue>
          </Card>
        </div>
        </div>
      </Layouts>
    </Fragment>
  );
}
