import React, { Fragment, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Layouts from "@components/layouts/index";
import Card from "@components/card";
import CardBlue from "@components/cardBlue";
import Btn_H_sms from "@components/btn_header_sms";
import Btn_link from "@components/btn_link";
import {
  Flex,
  Heading,
  Box,
  Link,
  Spacer,
  Text,
  Input,
  Grid,
  GridItem,
  Tabs,
  TabList,
  TabPanels,
  Tab,
  TabPanel,
  useTab,
  useMultiStyleConfig,
  Button,
  Center,
  Checkbox,
  CheckboxGrou,
  Stack
} from "@chakra-ui/react";
import Save_template from "@components/Modal/save_template"
import ChooseTemplate from "@components/Modal/chooseTemplate"
import ConfirmSender from '@components/Modal/confirmSender';

export default function Sms_preview_sender() {


  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layouts>
        <div className="page-content page-container">
        <div className='padding'>
          <Btn_H_sms></Btn_H_sms>
          <br />
          <Card>
            <CardBlue>
            <Flex>
              <Box>
                <Btn_link title="ย้อนกลับ" url="/sms_service/sms_sender"/>
              </Box>
            </Flex>
              <div className="row">
                <div className="col-md-8 ">
                  <Box>
                    
                    <Box m={[5,5,5,5]}>
                    <Box mb='5'>
                    <Flex justifyContent="center" gap="2">
                    <div className="item_head_icon top_15">
                      <a className={'active_bg_blue tb_btn btn_radius btn btn-white btn-sender-fix'} >พิมพ์ข้อความ</a>
                  </div>
                  <div className="item_head_icon top_15">
                      <ChooseTemplate/>
                  </div>
                      </Flex>
                  </Box>
                    <textarea
                      class="form-control auto_height btn_radius"
                      rows="9"
                      data-minwords="6"
                      required=""
                      placeholder="กรอกเบอร์โทรศัพท์ บรรทัดละ 1 เบอร์ ตัวอย่าง 0877777777"
                      value='โปรโมชั่นพิเศษ 9.9 ลูกค้าเก่าลดทันที 40% คลิ๊ก https://xxxxxxxx.com'
                    ></textarea>
                    
                    
                    <Save_template/>
                    </Box>
                    <Flex justifyContent="center" gap="2">
                    <button class="btn btn-sender-fix btn_radius mb-1 btn-md btn-white">
                    <div className="d-flex">
                      <span>
                        <img
                          className="w-50 "
                          src="/image/icon_3/font.png"
                        />
                      </span>
                      <div className="mx-3 ">
                        <strong className="phone_item_new">
                          จำนวนตัวอักษร
                        </strong>
                        <small className="strong_new_price">68</small>
                      </div>
                    </div>
                  </button>
                  <button class="btn btn-sender-fix btn_radius mb-1 btn-md btn-white">
                    <div className="d-flex">
                      <span>
                        <img
                          className="w-50 "
                          src="/image/icon_3/text-message (1).png"
                        />
                      </span>
                      <div className="mx-3 ">
                        <strong className="phone_item_new">
                          จำนวนเครดิตที่ใช้
                        </strong>
                        <small className="strong_new_price">1</small>
                      </div>
                    </div>
                  </button>
                    </Flex>
                  </Box>
                </div>
                <div className="col-md-4 ">
                <Text fontSize='xl' className="text-center" mt={5}> ตัวอย่างข้อความ</Text>
                    
                    <Box>
                    <Box maxW="sm"
                    className="position_text_example"
        borderRadius="xl"
        overflow="hidden"
        bg="#e2f4fe">
                    <Text fontSize='lg'> โปรโมชั่นพิเศษ 9.9 ลูกค้าเก่าลดทันที 40% คลิ๊ก https://xxxxxxxx.com</Text>
                    </Box>
                    <img
                      width="100%"
                      className="flu-id"
                      src="/image/icon_3/preview.png"
                    />
                    </Box>
                </div>
                <div className="col-md-12">
                <Flex justify="right" mt='5'>
                  <ConfirmSender/>
                  </Flex>
                  </div>
              </div>
            </CardBlue>
          </Card>
        </div>
        </div>
      </Layouts>
    </Fragment>
  );
}
